name: Obsidian2Foundry Foundry Module

permissions:
  contents: write  # Add this
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to use for release'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Zip output
        run: |
          mkdir obsidian2foundry
          mkdir obsidian2foundry/scripts
          mkdir obsidian2foundry/styles
          mkdir obsidian2foundry/lang
          cp module.json ./obsidian2foundry/
          cp ./styles/*.css ./obsidian2foundry/styles/
          cp ./scripts/main.js ./obsidian2foundry/scripts/
          zip -r obsidian2foundry.zip obsidian2foundry

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Handle both trigger types, github.event.inputs.tag is for getting the tag manual. If not found the automatic tag retrieval is used.
          # input events are only available for manual events aka workflow_dispatch events.
          tag="${{ github.event.inputs.tag || github.ref_name }}"
          
          gh release create "$tag" \
            --title="Release $tag" \
            --draft \
            module.json obsidian2foundry.zip